blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/OneIdentity/SafeguardCustomPlatform/tree/master/docs
    about: Browse the documentation for answers before opening an issue
